export const INIT_FETCH = 'INIT_FETCH';
export const LIST_FETCH_DATA_SUCCESS = 'LIST_FETCH_DATA_SUCCESS';
export const FILL_FILTERS = 'FILL_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const GET_FILTERED_LIST = 'GET_FILTERED_LIST';
export const GET_FILTERED_FIELDS = 'GET_FILTERED_FIELDS';

export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
export const LOADING_TOKEN = 'LOADING_TOKEN';


export const LOADING = 'LOADING';